# This file was generated by GoReleaser. DO NOT EDIT.
cask "brewrig" do
  version "1.22.0"

  on_macos do
    on_arm do
      sha256 "8145391ebfeaf96f81efeed80df79ac1e91da5eed28ffaabeafeeaa853c4416f"
      url "https://github.com/rigsmith/rigsmith/releases/download/v#{version}/brewrig_#{version}_darwin_arm64.tar.gz"
    end
    on_intel do
      sha256 "bde4bada97f601523e0f2550b6e2940ceb7934d8fc9478955d00833d5770ac5a"
      url "https://github.com/rigsmith/rigsmith/releases/download/v#{version}/brewrig_#{version}_darwin_amd64.tar.gz"
    end
  end
  on_linux do
    on_arm do
      sha256 "77967b18d4ca3ec526de4acb569494fa4b9b8e62095abe825c9aec4c06d8e44f"
      url "https://github.com/rigsmith/rigsmith/releases/download/v#{version}/brewrig_#{version}_linux_arm64.tar.gz"
    end
    on_intel do
      sha256 "687dc8ea99f581ecf674f3521e0cab15dd40525e1d3e59c2748c0e9904d8ff08"
      url "https://github.com/rigsmith/rigsmith/releases/download/v#{version}/brewrig_#{version}_linux_amd64.tar.gz"
    end
  end

  name "brewrig"
  desc "Keep several machines on the same Homebrew software, and the same versions of it"
  homepage "https://rigsmith.dev"

  livecheck do
    skip "Auto-generated on release."
  end

  binary "brewrig"

  # No zap stanza required
end
