# This file was generated by GoReleaser. DO NOT EDIT.
cask "brewrig" do
  version "1.20.3"

  on_macos do
    on_arm do
      sha256 "3d31123b851956d5f0a2cbab281b28b3a24acca4b0b2732b8c706661caef4a80"
      url "https://github.com/rigsmith/rigsmith/releases/download/v#{version}/brewrig_#{version}_darwin_arm64.tar.gz"
    end
    on_intel do
      sha256 "5dcf0f1e4e1a61eb08fdfb4cfdb109a9f88920975e1b151f2ac0bdc0087c10d5"
      url "https://github.com/rigsmith/rigsmith/releases/download/v#{version}/brewrig_#{version}_darwin_amd64.tar.gz"
    end
  end
  on_linux do
    on_arm do
      sha256 "27cb01c23ade6df8e829f921f42f76ffef238791a5ae1cc30f8116792ba94a7f"
      url "https://github.com/rigsmith/rigsmith/releases/download/v#{version}/brewrig_#{version}_linux_arm64.tar.gz"
    end
    on_intel do
      sha256 "e6268af06404448450c6e50e99d069713c3bc1453c1eb2cddff0c3514bb0f708"
      url "https://github.com/rigsmith/rigsmith/releases/download/v#{version}/brewrig_#{version}_linux_amd64.tar.gz"
    end
  end

  name "brewrig"
  desc "Keep several machines on the same Homebrew software, and the same versions of it"
  homepage "https://rigsmith.dev"

  livecheck do
    skip "Auto-generated on release."
  end

  binary "brewrig"

  # No zap stanza required
end
