# This file was generated by GoReleaser. DO NOT EDIT.
cask "brewrig" do
  version "1.23.0"

  on_macos do
    on_arm do
      sha256 "a3660fe09abae8940a7c8b39f75301f1878bb12b5dbd7f996f035c9520a5f8db"
      url "https://github.com/rigsmith/rigsmith/releases/download/v#{version}/brewrig_#{version}_darwin_arm64.tar.gz"
    end
    on_intel do
      sha256 "4d56d86aee90f30bf557edfba32bed63eb2dca4226cf0f5e38ec449e746cdc46"
      url "https://github.com/rigsmith/rigsmith/releases/download/v#{version}/brewrig_#{version}_darwin_amd64.tar.gz"
    end
  end
  on_linux do
    on_arm do
      sha256 "0ecdc75ed1bd687146d6d5646d8db1ae8a5a1997b590d7930e696bd33549a036"
      url "https://github.com/rigsmith/rigsmith/releases/download/v#{version}/brewrig_#{version}_linux_arm64.tar.gz"
    end
    on_intel do
      sha256 "ab871cc919b3044c36b3864071ebda5e5ee85e820280c1ea6b093735912cfc33"
      url "https://github.com/rigsmith/rigsmith/releases/download/v#{version}/brewrig_#{version}_linux_amd64.tar.gz"
    end
  end

  name "brewrig"
  desc "Keep several machines on the same Homebrew software, and the same versions of it"
  homepage "https://rigsmith.dev"

  livecheck do
    skip "Auto-generated on release."
  end

  binary "brewrig"

  # No zap stanza required
end
