# This file was generated by GoReleaser. DO NOT EDIT.
cask "changerig" do
  version "1.5.0"

  on_macos do
    on_intel do
      sha256 "08e1e8f84d0f7b03e44317f818833aa278ce550959ab284f4e84e8aa892b9df6"
      url "https://github.com/rigsmith/rigsmith/releases/download/v#{version}/changerig_#{version}_darwin_amd64.tar.gz"
    end
    on_arm do
      sha256 "114ba9b49de392027e70ef10630ae8c5a6d203f8d7b6ad4e61fad206a4a1299d"
      url "https://github.com/rigsmith/rigsmith/releases/download/v#{version}/changerig_#{version}_darwin_arm64.tar.gz"
    end
  end

  on_linux do
    on_intel do
      sha256 "5609c9a52ae8086cbf47daeaf285c54b0028230e38e9a58c2e632ec882ebe460"
      url "https://github.com/rigsmith/rigsmith/releases/download/v#{version}/changerig_#{version}_linux_amd64.tar.gz"
    end
    on_arm do
      sha256 "0fa09b8023a95679868f021dbf4085fc538f0e16894779ba126bd941b3aa6925"
      url "https://github.com/rigsmith/rigsmith/releases/download/v#{version}/changerig_#{version}_linux_arm64.tar.gz"
    end
  end

  name "changerig"
  desc "Changesets: capture intent, then version across every ecosystem"
  homepage "https://rigsmith.dev"

  livecheck do
    skip "Auto-generated on release."
  end

  binary "changerig"

  postflight do
    if system_command("/usr/bin/xattr", args: ["-h"]).exit_status == 0
      system_command "/usr/bin/xattr", args: ["-dr", "com.apple.quarantine", "#{staged_path}/changerig"]
    end
  end

  # No zap stanza required

end
