# This file was generated by GoReleaser. DO NOT EDIT.
cask "changerig" do
  version "1.10.0"

  on_macos do
    on_arm do
      sha256 "571261cae0718feb6430c69458b3cdfc0f4e9a1a31c83878e747bac8d4abac24"
      url "https://github.com/rigsmith/rigsmith/releases/download/v#{version}/changerig_#{version}_darwin_arm64.tar.gz"
    end
    on_intel do
      sha256 "85d8b99895d36242b247bcfb36cb85dba27ce600c4d6fbf14f529dc4e31094c1"
      url "https://github.com/rigsmith/rigsmith/releases/download/v#{version}/changerig_#{version}_darwin_amd64.tar.gz"
    end
  end
  on_linux do
    on_arm do
      sha256 "08f661c4b29fd41918bc1075216713d9f0e3e0943530bfcf2d8e8e57ef36e226"
      url "https://github.com/rigsmith/rigsmith/releases/download/v#{version}/changerig_#{version}_linux_arm64.tar.gz"
    end
    on_intel do
      sha256 "7dd0042bb3e07af0d5008ef2900ce17837da4bac25f39f1142e64de3a9a3e2d0"
      url "https://github.com/rigsmith/rigsmith/releases/download/v#{version}/changerig_#{version}_linux_amd64.tar.gz"
    end
  end

  name "changerig"
  desc "Changesets: capture intent, then version across every ecosystem"
  homepage "https://rigsmith.dev"

  livecheck do
    skip "Auto-generated on release."
  end

  binary "changerig"

  postflight do
    if system_command("/usr/bin/xattr", args: ["-h"]).exit_status == 0
      system_command "/usr/bin/xattr", args: ["-dr", "com.apple.quarantine", "#{staged_path}/changerig"]
    end
  end

  # No zap stanza required
end
