# This file was generated by GoReleaser. DO NOT EDIT.
cask "changerig" do
  version "1.3.0"

  on_macos do
    on_intel do
      sha256 "2dc7d43cc9abfa994e9fdd9b9fac5d34363e14019b9c3f7805ed40c6b3c867e6"
      url "https://github.com/rigsmith/rigsmith/releases/download/v#{version}/changerig_#{version}_darwin_amd64.tar.gz"
    end
    on_arm do
      sha256 "402f5892036764e60d6269a83ca78d6ccdad590d3d9304004a26111ba9b464e0"
      url "https://github.com/rigsmith/rigsmith/releases/download/v#{version}/changerig_#{version}_darwin_arm64.tar.gz"
    end
  end

  on_linux do
    on_intel do
      sha256 "c06bcbfd4c1ce0195cd415eb304aa866b0784a74985f186468ae0cc96116c40f"
      url "https://github.com/rigsmith/rigsmith/releases/download/v#{version}/changerig_#{version}_linux_amd64.tar.gz"
    end
    on_arm do
      sha256 "370ca413b3dc58fb9e8a7ab70feec3c45f5f7497c667a5ef1e84a3efa0dd0a1b"
      url "https://github.com/rigsmith/rigsmith/releases/download/v#{version}/changerig_#{version}_linux_arm64.tar.gz"
    end
  end

  name "changerig"
  desc "Changesets: capture intent, then version across every ecosystem"
  homepage "https://rigsmith.dev"

  livecheck do
    skip "Auto-generated on release."
  end

  binary "changerig"

  postflight do
    if system_command("/usr/bin/xattr", args: ["-h"]).exit_status == 0
      system_command "/usr/bin/xattr", args: ["-dr", "com.apple.quarantine", "#{staged_path}/changerig"]
    end
  end

  # No zap stanza required

end
