# This file was generated by GoReleaser. DO NOT EDIT.
cask "clauderig" do
  version "1.2.0"

  on_macos do
    on_intel do
      sha256 "096b8afda4b0f83b9852b3ebb4d06e823fab0ac345c20741fa9fbc8dd2565510"
      url "https://github.com/rigsmith/rigsmith/releases/download/v#{version}/clauderig_#{version}_darwin_amd64.tar.gz"
    end
    on_arm do
      sha256 "a3c84e28039222e3e2edf0f3dd9ea6018f62ba5b272a10b2c1f23596a96b3a9d"
      url "https://github.com/rigsmith/rigsmith/releases/download/v#{version}/clauderig_#{version}_darwin_arm64.tar.gz"
    end
  end

  on_linux do
    on_intel do
      sha256 "b4f6c2dd49f00d0c166f3f04c4457b9ee5c930fead8b603d82fe606224d2a3fe"
      url "https://github.com/rigsmith/rigsmith/releases/download/v#{version}/clauderig_#{version}_linux_amd64.tar.gz"
    end
    on_arm do
      sha256 "0f4fe23ec3c02a32d40d9d8aecbeaa104156cd9b8e8a042f841ca28f771162d9"
      url "https://github.com/rigsmith/rigsmith/releases/download/v#{version}/clauderig_#{version}_linux_arm64.tar.gz"
    end
  end

  name "clauderig"
  desc "Sync your Claude Code setup across machines, path-correct on restore"
  homepage "https://rigsmith.dev"

  livecheck do
    skip "Auto-generated on release."
  end

  binary "clauderig"

  postflight do
    if system_command("/usr/bin/xattr", args: ["-h"]).exit_status == 0
      system_command "/usr/bin/xattr", args: ["-dr", "com.apple.quarantine", "#{staged_path}/clauderig"]
    end
  end

  # No zap stanza required

end
