# This file was generated by GoReleaser. DO NOT EDIT.
cask "clauderig" do
  version "1.19.0"

  on_macos do
    on_arm do
      sha256 "47c45ab8f75bfd535a40f473613ab1885c28e7a454aa1ade9b7d9a94f7cd33b7"
      url "https://github.com/rigsmith/rigsmith/releases/download/v#{version}/clauderig_#{version}_darwin_arm64.tar.gz"
    end
    on_intel do
      sha256 "a035788d962d4f41fe94184487f1f68f24b692ca84e0706de42f1e4aa0f76afb"
      url "https://github.com/rigsmith/rigsmith/releases/download/v#{version}/clauderig_#{version}_darwin_amd64.tar.gz"
    end
  end
  on_linux do
    on_arm do
      sha256 "c132eb15c9838ca7d0249ba6675a48cc0e96dc8d9261a8abb2f9557b6b3b51ea"
      url "https://github.com/rigsmith/rigsmith/releases/download/v#{version}/clauderig_#{version}_linux_arm64.tar.gz"
    end
    on_intel do
      sha256 "eeb0efbce8f3dfe4653af717bf1e24770a0e185579d32e9be0bb16b9ae9d7287"
      url "https://github.com/rigsmith/rigsmith/releases/download/v#{version}/clauderig_#{version}_linux_amd64.tar.gz"
    end
  end

  name "clauderig"
  desc "Sync your Claude Code configuration across machines, path-correct on restore"
  homepage "https://rigsmith.dev"

  livecheck do
    skip "Auto-generated on release."
  end

  binary "clauderig"

  # No zap stanza required
end
