# This file was generated by GoReleaser. DO NOT EDIT.
cask "clauderig" do
  version "1.16.0"

  on_macos do
    on_arm do
      sha256 "9504a7207af8fb3af6b8b059c7b776d631dc6b02465922e912445247a2212907"
      url "https://github.com/rigsmith/rigsmith/releases/download/v#{version}/clauderig_#{version}_darwin_arm64.tar.gz"
    end
    on_intel do
      sha256 "3e09debb0ad790f22b869dc3ab606516f4d30d515a82a8a0a1894d5549227a27"
      url "https://github.com/rigsmith/rigsmith/releases/download/v#{version}/clauderig_#{version}_darwin_amd64.tar.gz"
    end
  end
  on_linux do
    on_arm do
      sha256 "25a8a4157e8783a156ba77cc69a8bd4c77dfaac16c35467f7deea09e8623b6ea"
      url "https://github.com/rigsmith/rigsmith/releases/download/v#{version}/clauderig_#{version}_linux_arm64.tar.gz"
    end
    on_intel do
      sha256 "fd769fd2edad2ed5c6b01a938daa060b8059ede17ee1b619870fba1eec81e8c0"
      url "https://github.com/rigsmith/rigsmith/releases/download/v#{version}/clauderig_#{version}_linux_amd64.tar.gz"
    end
  end

  name "clauderig"
  desc "Sync your Claude Code configuration across machines, path-correct on restore"
  homepage "https://rigsmith.dev"

  livecheck do
    skip "Auto-generated on release."
  end

  binary "clauderig"

  postflight do
    if system_command("/usr/bin/xattr", args: ["-h"]).exit_status == 0
      system_command "/usr/bin/xattr", args: ["-dr", "com.apple.quarantine", "#{staged_path}/clauderig"]
    end
  end

  # No zap stanza required
end
