# This file was generated by GoReleaser. DO NOT EDIT.
cask "codexrig" do
  version "1.19.0"

  on_macos do
    on_arm do
      sha256 "a57dfc209694a966496b0c4e9a04dcb5b045a220e93a981cefb5d936b865582e"
      url "https://github.com/rigsmith/rigsmith/releases/download/v#{version}/codexrig_#{version}_darwin_arm64.tar.gz"
    end
    on_intel do
      sha256 "e67fb00bf3019ebe06bca9f51b5e959f9aa364bc0434e3ec27f937eb1a0a2c11"
      url "https://github.com/rigsmith/rigsmith/releases/download/v#{version}/codexrig_#{version}_darwin_amd64.tar.gz"
    end
  end
  on_linux do
    on_arm do
      sha256 "2b246dda9a094222ca0c165afc229606de46641ab8a191245f436d3b6c0afdbe"
      url "https://github.com/rigsmith/rigsmith/releases/download/v#{version}/codexrig_#{version}_linux_arm64.tar.gz"
    end
    on_intel do
      sha256 "3c1b82a7d8a48e2e10b4fba92facab14f7d492e9cc06e465035ff8f3853e68f6"
      url "https://github.com/rigsmith/rigsmith/releases/download/v#{version}/codexrig_#{version}_linux_amd64.tar.gz"
    end
  end

  name "codexrig"
  desc "Sync your Codex CLI configuration across machines, and run several logins side by side"
  homepage "https://rigsmith.dev"

  livecheck do
    skip "Auto-generated on release."
  end

  binary "codexrig"

  # No zap stanza required
end
