# This file was generated by GoReleaser. DO NOT EDIT.
cask "codexrig" do
  version "1.20.2"

  on_macos do
    on_arm do
      sha256 "eeea4053800dc7b9fa97a4612c0a19a32932116a78adc696be020502af618e65"
      url "https://github.com/rigsmith/rigsmith/releases/download/v#{version}/codexrig_#{version}_darwin_arm64.tar.gz"
    end
    on_intel do
      sha256 "689b51f5872e8b3ad3ce156e1b9d15f9977cc311c97a84c59a58f01af38d38b2"
      url "https://github.com/rigsmith/rigsmith/releases/download/v#{version}/codexrig_#{version}_darwin_amd64.tar.gz"
    end
  end
  on_linux do
    on_arm do
      sha256 "4b5342756374bbc48f8fcf241a95ff98e70dd433cce889730f1628200b24bc36"
      url "https://github.com/rigsmith/rigsmith/releases/download/v#{version}/codexrig_#{version}_linux_arm64.tar.gz"
    end
    on_intel do
      sha256 "0943a1adf8c696283a72a3bbb4f022ea31380be8bf5f7e6b2bffa8d012d841d4"
      url "https://github.com/rigsmith/rigsmith/releases/download/v#{version}/codexrig_#{version}_linux_amd64.tar.gz"
    end
  end

  name "codexrig"
  desc "Sync your Codex CLI configuration across machines, and run several logins side by side"
  homepage "https://rigsmith.dev"

  livecheck do
    skip "Auto-generated on release."
  end

  binary "codexrig"

  # No zap stanza required
end
