# This file was generated by GoReleaser. DO NOT EDIT.
cask "codexrig" do
  version "1.20.1"

  on_macos do
    on_arm do
      sha256 "61a62c53c692272a86598edb5e9c43d2bd245251058eb64f6fdc23f19f7850bd"
      url "https://github.com/rigsmith/rigsmith/releases/download/v#{version}/codexrig_#{version}_darwin_arm64.tar.gz"
    end
    on_intel do
      sha256 "9f85e4625eb68d84b8eeaa5a2397f4416708f33da4b7b8552018b0247be82015"
      url "https://github.com/rigsmith/rigsmith/releases/download/v#{version}/codexrig_#{version}_darwin_amd64.tar.gz"
    end
  end
  on_linux do
    on_arm do
      sha256 "5f7f4a5974c8dcb74f82e5f3076f13175270597ef81de0e20fc332f58e32e06c"
      url "https://github.com/rigsmith/rigsmith/releases/download/v#{version}/codexrig_#{version}_linux_arm64.tar.gz"
    end
    on_intel do
      sha256 "e7df399d6d9ef4c5c42071c8a265f676643c2c8611bce17b36c24ab0d8f6c07e"
      url "https://github.com/rigsmith/rigsmith/releases/download/v#{version}/codexrig_#{version}_linux_amd64.tar.gz"
    end
  end

  name "codexrig"
  desc "Sync your Codex CLI configuration across machines, and run several logins side by side"
  homepage "https://rigsmith.dev"

  livecheck do
    skip "Auto-generated on release."
  end

  binary "codexrig"

  # No zap stanza required
end
