# This file was generated by GoReleaser. DO NOT EDIT.
cask "rig" do
  version "1.13.0"

  on_macos do
    on_arm do
      sha256 "79f426ffea7005b8efe0d0e36358b1723b6b29711ffe548f0e333a8a7bbd2fd9"
      url "https://github.com/rigsmith/rigsmith/releases/download/v#{version}/rig_#{version}_darwin_arm64.tar.gz"
    end
    on_intel do
      sha256 "b64427469e34ae8f6a2c50569f8b4807c6a05b8b29f6ce107098b55254cfc7da"
      url "https://github.com/rigsmith/rigsmith/releases/download/v#{version}/rig_#{version}_darwin_amd64.tar.gz"
    end
  end
  on_linux do
    on_arm do
      sha256 "56a7221785c46d79c58ce80b8af1b30a136dba561fc3f5d086ebdde8738ebb76"
      url "https://github.com/rigsmith/rigsmith/releases/download/v#{version}/rig_#{version}_linux_arm64.tar.gz"
    end
    on_intel do
      sha256 "e900e898fb20dab276f62eef57dd337be0251b66c94d6edb34c49a2163d65727"
      url "https://github.com/rigsmith/rigsmith/releases/download/v#{version}/rig_#{version}_linux_amd64.tar.gz"
    end
  end

  name "rig"
  desc "Convention-first dev launcher across .NET, Node, Go, and Rust"
  homepage "https://rigsmith.dev"

  livecheck do
    skip "Auto-generated on release."
  end

  binary "rig"

  postflight do
    if system_command("/usr/bin/xattr", args: ["-h"]).exit_status == 0
      system_command "/usr/bin/xattr", args: ["-dr", "com.apple.quarantine", "#{staged_path}/rig"]
    end
  end

  # No zap stanza required
end
