# This file was generated by GoReleaser. DO NOT EDIT.
cask "rig" do
  version "1.5.2"

  on_macos do
    on_intel do
      sha256 "8cbd4078a58962b58160775d6b775f305c26a50928ee76649cd21bd062a908db"
      url "https://github.com/rigsmith/rigsmith/releases/download/v#{version}/rig_#{version}_darwin_amd64.tar.gz"
    end
    on_arm do
      sha256 "e31a42c8e804e4573a0b4ae807590ce5b077e5956f28681e731a6c9bdc2f51a6"
      url "https://github.com/rigsmith/rigsmith/releases/download/v#{version}/rig_#{version}_darwin_arm64.tar.gz"
    end
  end

  on_linux do
    on_intel do
      sha256 "92e7e061a20c503a06ae78bcd2111d550168985233685cca2e2f2c67f4240e79"
      url "https://github.com/rigsmith/rigsmith/releases/download/v#{version}/rig_#{version}_linux_amd64.tar.gz"
    end
    on_arm do
      sha256 "0477ad4c390f89011a743108ccec1d72699408f3f10c4b177b890ddb72507f68"
      url "https://github.com/rigsmith/rigsmith/releases/download/v#{version}/rig_#{version}_linux_arm64.tar.gz"
    end
  end

  name "rig"
  desc "Convention-first dev launcher across .NET, Node, Go, and Rust"
  homepage "https://rigsmith.dev"

  livecheck do
    skip "Auto-generated on release."
  end

  binary "rig"

  postflight do
    if system_command("/usr/bin/xattr", args: ["-h"]).exit_status == 0
      system_command "/usr/bin/xattr", args: ["-dr", "com.apple.quarantine", "#{staged_path}/rig"]
    end
  end

  # No zap stanza required

end
