# This file was generated by GoReleaser. DO NOT EDIT.
cask "rig" do
  version "1.1.0"

  on_macos do
    on_intel do
      sha256 "891804486fa68005a1e3273f82157c0036e6981f6988d467ac0d528c6fe1bb74"
      url "https://github.com/rigsmith/rigsmith/releases/download/v#{version}/rig_#{version}_darwin_amd64.tar.gz"
    end
    on_arm do
      sha256 "9d1de52226210d11368eb3f2dfb2f789b3e9228a1ea74d8bca4116b72fe9cf10"
      url "https://github.com/rigsmith/rigsmith/releases/download/v#{version}/rig_#{version}_darwin_arm64.tar.gz"
    end
  end

  on_linux do
    on_intel do
      sha256 "d2670a3c882947e5ce1366ab78ca05ace27b9ed34038d304865be3a27fdeb4fd"
      url "https://github.com/rigsmith/rigsmith/releases/download/v#{version}/rig_#{version}_linux_amd64.tar.gz"
    end
    on_arm do
      sha256 "10b90542174a4743f5222aa01098cfe2923d19a7360f7a4b14ae89080fde8724"
      url "https://github.com/rigsmith/rigsmith/releases/download/v#{version}/rig_#{version}_linux_arm64.tar.gz"
    end
  end

  name "rig"
  desc "Convention-first dev launcher across .NET, Node, Go, and Rust"
  homepage "https://rigsmith.dev"

  livecheck do
    skip "Auto-generated on release."
  end

  binary "rig"

  postflight do
    if system_command("/usr/bin/xattr", args: ["-h"]).exit_status == 0
      system_command "/usr/bin/xattr", args: ["-dr", "com.apple.quarantine", "#{staged_path}/rig"]
    end
  end

  # No zap stanza required

end
