# This file was generated by GoReleaser. DO NOT EDIT.
cask "rigsmith" do
  version "1.18.0"

  on_macos do
    on_arm do
      sha256 "7c27c7adf1ed48758049f96ab4044976826b35426c809a751efa14df73e02b9b"
      url "https://github.com/rigsmith/rigsmith/releases/download/v#{version}/rigsmith_#{version}_darwin_arm64.tar.gz"
    end
    on_intel do
      sha256 "52afcd52845e9051d02d474012f9fb6e7a7745cd89515679dc262b71f1b4a022"
      url "https://github.com/rigsmith/rigsmith/releases/download/v#{version}/rigsmith_#{version}_darwin_amd64.tar.gz"
    end
  end
  on_linux do
    on_arm do
      sha256 "ac40432d9978ded6fca41743b3a0735af708af4ccbd7ed2b23b4f9882f3643cc"
      url "https://github.com/rigsmith/rigsmith/releases/download/v#{version}/rigsmith_#{version}_linux_arm64.tar.gz"
    end
    on_intel do
      sha256 "292807a688858deee40271cf5a89863873dc87e4e15e1f0308869dd690e73360"
      url "https://github.com/rigsmith/rigsmith/releases/download/v#{version}/rigsmith_#{version}_linux_amd64.tar.gz"
    end
  end

  name "rigsmith"
  desc "The rigsmith toolchain: rig, changerig, shiprig, clauderig"
  homepage "https://rigsmith.dev"

  livecheck do
    skip "Auto-generated on release."
  end

  binary "rig"
  binary "changerig"
  binary "shiprig"
  binary "clauderig"

  postflight do
    if system_command("/usr/bin/xattr", args: ["-h"]).exit_status == 0
      system_command "/usr/bin/xattr", args: ["-dr", "com.apple.quarantine", staged_path.to_s]
    end
  end

  # No zap stanza required
end
