# This file was generated by GoReleaser. DO NOT EDIT.
cask "rigsmith" do
  version "1.15.4"

  on_macos do
    on_arm do
      sha256 "677930c13660d46d42c7d47f643c9af47c15edf56b1ad5ca99836e577d18fdd4"
      url "https://github.com/rigsmith/rigsmith/releases/download/v#{version}/rigsmith_#{version}_darwin_arm64.tar.gz"
    end
    on_intel do
      sha256 "e89f676612d773add49da5702e198d50cdfec8d40f75639b35ba3f57b2f70335"
      url "https://github.com/rigsmith/rigsmith/releases/download/v#{version}/rigsmith_#{version}_darwin_amd64.tar.gz"
    end
  end
  on_linux do
    on_arm do
      sha256 "98078da4cf7953afdaee83a0a17472a0bf3357c2a1602735dfd5a52f656f3ea4"
      url "https://github.com/rigsmith/rigsmith/releases/download/v#{version}/rigsmith_#{version}_linux_arm64.tar.gz"
    end
    on_intel do
      sha256 "44d4cf590ad709e9d44bbbb44c514daf884c74b8d9205d806e4ac8303676ad49"
      url "https://github.com/rigsmith/rigsmith/releases/download/v#{version}/rigsmith_#{version}_linux_amd64.tar.gz"
    end
  end

  name "rigsmith"
  desc "The rigsmith toolchain: rig, changerig, shiprig, clauderig"
  homepage "https://rigsmith.dev"

  livecheck do
    skip "Auto-generated on release."
  end

  binary "rig"
  binary "changerig"
  binary "shiprig"
  binary "clauderig"

  postflight do
    if system_command("/usr/bin/xattr", args: ["-h"]).exit_status == 0
      system_command "/usr/bin/xattr", args: ["-dr", "com.apple.quarantine", staged_path.to_s]
    end
  end

  # No zap stanza required
end
