# This file was generated by GoReleaser. DO NOT EDIT.
cask "rigsmith" do
  version "1.13.1"

  on_macos do
    on_arm do
      sha256 "cd272c2224947c0afa2a47c4c3003c81bcc285220b168b4a4d03002ee284b8dc"
      url "https://github.com/rigsmith/rigsmith/releases/download/v#{version}/rigsmith_#{version}_darwin_arm64.tar.gz"
    end
    on_intel do
      sha256 "62b0529662a19a7f591b8803a2c6ac3e6dbecfb4224832aa800f5ef319d34ebe"
      url "https://github.com/rigsmith/rigsmith/releases/download/v#{version}/rigsmith_#{version}_darwin_amd64.tar.gz"
    end
  end
  on_linux do
    on_arm do
      sha256 "ac3e8d32597ed3c9f97c039292697d65447fa4093d952419d5761f4121e014e6"
      url "https://github.com/rigsmith/rigsmith/releases/download/v#{version}/rigsmith_#{version}_linux_arm64.tar.gz"
    end
    on_intel do
      sha256 "d38608c340b3d63a6f87dd9b5b15f00f3dd3acf0693781758f96a3343ca3cd8f"
      url "https://github.com/rigsmith/rigsmith/releases/download/v#{version}/rigsmith_#{version}_linux_amd64.tar.gz"
    end
  end

  name "rigsmith"
  desc "The rigsmith toolchain: rig, changerig, shiprig, clauderig"
  homepage "https://rigsmith.dev"

  livecheck do
    skip "Auto-generated on release."
  end

  binary "rig"
  binary "changerig"
  binary "shiprig"
  binary "clauderig"

  postflight do
    if system_command("/usr/bin/xattr", args: ["-h"]).exit_status == 0
      system_command "/usr/bin/xattr", args: ["-dr", "com.apple.quarantine", staged_path.to_s]
    end
  end

  # No zap stanza required
end
