# This file was generated by GoReleaser. DO NOT EDIT.
cask "shiprig" do
  version "1.15.1"

  on_macos do
    on_arm do
      sha256 "53551d1eb8091e1b966ec1e6750a36016ad1c5dcb69d15f949b864737c9f5a33"
      url "https://github.com/rigsmith/rigsmith/releases/download/v#{version}/shiprig_#{version}_darwin_arm64.tar.gz"
    end
    on_intel do
      sha256 "251059144da313eb0c0b477f3cf9e4a0b99a0913efeb2b8a1393280276888a10"
      url "https://github.com/rigsmith/rigsmith/releases/download/v#{version}/shiprig_#{version}_darwin_amd64.tar.gz"
    end
  end
  on_linux do
    on_arm do
      sha256 "3ffb7bba04a9449c296137c643b701e34cb2cd7c937b5af6de32bef16b804516"
      url "https://github.com/rigsmith/rigsmith/releases/download/v#{version}/shiprig_#{version}_linux_arm64.tar.gz"
    end
    on_intel do
      sha256 "77c592e1f64ae5b301e1388a41771823f86ac914c859e4e6fe5d9a2ef8cc5f2f"
      url "https://github.com/rigsmith/rigsmith/releases/download/v#{version}/shiprig_#{version}_linux_amd64.tar.gz"
    end
  end

  name "shiprig"
  desc "Uniform changeset -> version -> publish, across every ecosystem"
  homepage "https://rigsmith.dev"

  livecheck do
    skip "Auto-generated on release."
  end

  binary "shiprig"

  postflight do
    if system_command("/usr/bin/xattr", args: ["-h"]).exit_status == 0
      system_command "/usr/bin/xattr", args: ["-dr", "com.apple.quarantine", "#{staged_path}/shiprig"]
    end
  end

  # No zap stanza required
end
