# This file was generated by GoReleaser. DO NOT EDIT.
cask "shiprig" do
  version "1.20.1"

  on_macos do
    on_arm do
      sha256 "e1f09e995d26aaf782392df2ed6586e1036a3b86fd994ae2fb8b460b92144784"
      url "https://github.com/rigsmith/rigsmith/releases/download/v#{version}/shiprig_#{version}_darwin_arm64.tar.gz"
    end
    on_intel do
      sha256 "3293be7c975ffd50c3a42ed3f5b03f0bcca5758f5b4bef433c2026987499c60e"
      url "https://github.com/rigsmith/rigsmith/releases/download/v#{version}/shiprig_#{version}_darwin_amd64.tar.gz"
    end
  end
  on_linux do
    on_arm do
      sha256 "330a750a913f1d53e82be7938e16db50e18e4f3538ffd0f0876fdc1f9bdbc995"
      url "https://github.com/rigsmith/rigsmith/releases/download/v#{version}/shiprig_#{version}_linux_arm64.tar.gz"
    end
    on_intel do
      sha256 "566803ee48885caa3605317c7b731fb33388ed1aff3e692fccf16d248e5f7f41"
      url "https://github.com/rigsmith/rigsmith/releases/download/v#{version}/shiprig_#{version}_linux_amd64.tar.gz"
    end
  end

  name "shiprig"
  desc "Uniform changeset -> version -> publish, across every ecosystem"
  homepage "https://rigsmith.dev"

  livecheck do
    skip "Auto-generated on release."
  end

  binary "shiprig"

  # No zap stanza required
end
