# This file was generated by GoReleaser. DO NOT EDIT.
cask "shiprig" do
  version "1.22.0"

  on_macos do
    on_arm do
      sha256 "a259f55f304b814b28fe7e7d84d954b8454012edab4a9af9e208b153d0bac23b"
      url "https://github.com/rigsmith/rigsmith/releases/download/v#{version}/shiprig_#{version}_darwin_arm64.tar.gz"
    end
    on_intel do
      sha256 "1f034f7404faa5e5a880e158e86c9f57dca04fc4322e7a828a73e9d6e5f76058"
      url "https://github.com/rigsmith/rigsmith/releases/download/v#{version}/shiprig_#{version}_darwin_amd64.tar.gz"
    end
  end
  on_linux do
    on_arm do
      sha256 "31eed2cee08031b596a9e4cbcda553399ebe1f436fced13d3c8764f40093d115"
      url "https://github.com/rigsmith/rigsmith/releases/download/v#{version}/shiprig_#{version}_linux_arm64.tar.gz"
    end
    on_intel do
      sha256 "55c6a3909df047f67b90a6df37825af91b9cc2e624c9ffa83b6d340e8bf2fe96"
      url "https://github.com/rigsmith/rigsmith/releases/download/v#{version}/shiprig_#{version}_linux_amd64.tar.gz"
    end
  end

  name "shiprig"
  desc "Uniform changeset -> version -> publish, across every ecosystem"
  homepage "https://rigsmith.dev"

  livecheck do
    skip "Auto-generated on release."
  end

  binary "shiprig"

  # No zap stanza required
end
